### ISSUE TITLE
error reading gapminder.lisp

### ISSUE THREAD

**Issue by slyrus** [Lisp-Stat/plot#13]
After some time trying to deal with the various unreleased dependencies of plot, I was able to get things mostly loading. However, I know get the following error:

```
end of file on #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}>
   [Condition of type END-OF-FILE]

Restarts:
 0: [RETRY] Retry EVAL of current toplevel form.
 1: [CONTINUE] Ignore error and continue loading file ".../quicklisp/local-projects/lisp-stat/data/gapminder.lisp".
 2: [ABORT] Abort loading file "/Users/CHarmon/quicklisp/local-projects/lisp-stat/data/gapminder.lisp".
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {700368E1F3}>)

Backtrace:
  0: (PEEK-CHAR NIL #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}> T NIL #<unused argument>)
  1: (YASON::PARSE-OBJECT #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}>)
  2: ((:METHOD YASON::PARSE% (STREAM)) #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}>) [fast-method]
  3: (YASON:PARSE #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}> :OBJECT-KEY-FN NIL :OBJECT-AS NIL :JSON-ARRAYS-AS-VECTORS NIL :JSON-BOOLEANS-AS-SYMBOLS NIL :JSON-NULLS-AS-KEYWORD NIL)
  4: (YASON::%PARSE-ARRAY #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}> #<FUNCTION (LAMBDA (YASON::ELEMENT) :IN YASON::PARSE-ARRAY) {703411EC9B}>)
  5: (YASON::PARSE-ARRAY #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}>)
  6: ((:METHOD YASON::PARSE% (STREAM)) #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}>) [fast-method]
  7: (YASON:PARSE #<DEXADOR.DECODING-STREAM:DECODING-STREAM {703411EB93}> :OBJECT-KEY-FN NIL :OBJECT-AS NIL :JSON-ARRAYS-AS-VECTORS NIL :JSON-BOOLEANS-AS-SYMBOLS NIL :JSON-NULLS-AS-KEYWORD NIL)
  8: (VEGA::JSON-TO-DATA-COLUMNS "http://raw.githubusercontent.com/vega/vega-datasets/master/data/gapminder.json" :MAP-ALIST (("" . :NA) ("NIL" . :NA)))
  9: (VEGA:READ-VEGA "http://raw.githubusercontent.com/vega/vega-datasets/master/data/gapminder.json" :MAP-ALIST (("" . :NA) ("NIL" . :NA)))

```

Is this a bona fide fproblem with the json file or do I just have the-latest-from-quicklisp-but-not-really-new-enough yason?

thanks!

**Comment by snunez1** [comment]
What platform are you on?  I just tried this on MS Windows 10:

```
LS-USER> (asdf:load-system :plot/vega)
; compilation output...
LS-USER> (data :gapminder)
T
```
I just had a look at the [raw data file](http://raw.githubusercontent.com/vega/vega-datasets/master/data/gapminder.json) and don't see anything unusual, except possibly the lack of a newline at the end?

My version of yason is yason-20220707, updated from quicklisp not too long ago (within the month).

My guess is that it's something to do with the file.  Try downloading it and loading from disk so that we can experiment with various line/file endings and ensure the syntax is correct.  It might possibly be a problem with Dexador too.

**Comment by slyrus** [comment]
Hmm... I'm on macOS 12.5.1 on SBCL. I'll start digging. Thanks!

**Comment by slyrus** [comment]
If I download the file and then load it, everything is fine. It's clearly not all of the vega example files as, e.g., barley works fine.

**Comment by Symbolics** [comment]
I wonder if there is a dexador option for this problem? @slyrus, did you find a solution?

**Comment by tobyWorland** [comment]
This was a bug in dexador and has since been fixed. It should work with the next dist of quicklisp.

In the meantime, you can either clone dexador locally or apply the attached patch to your local copy of [dfio](https://github.com/Lisp-Stat/dfio).

[dfio-patch.txt](https://github.com/Lisp-Stat/plot/files/9840230/dfio-patch.txt)

**Comment by Symbolics** [comment]
Thanks @tobyWorland. Closing.
