### ISSUE TITLE
Getting Started plot error

### ISSUE THREAD

**Issue by brandflake11** [Lisp-Stat/plot#17]
Hello,
I just discovered this awesome package and ran into a small issue when going through the Getting Started.

This is was I have evaluated in sbcl:
```
(ql:quickload :lisp-stat)
;; for plotting
(ql:quickload :plot/vega)

(in-package :ls-user)

(data :vgcars)

(plot:plot
 (vega:defplot hp-mpg
   `(:title "Horsepower vs. MPG"
     :description "Horsepower vs miles per gallon for various cars"
     :data ,vgcars
     :mark :point
     :encoding (:x (:field :horsepower :type :quantitative)
                :y (:field :miles-per-gallon :type :quantitative)))))
```
Everything evaluates without errors, except for the last part with PLOT, which returns this error:
```
The value
  nil
is not of type
  (or string pathname synonym-stream file-stream)
when binding pathname
   [Condition of type type-error]

Restarts:
 0: [retry] Retry SLIME interactive evaluation request.
 1: [*abort] Return to SLIME's top level.
 2: [abort] abort thread (#<thread "worker" running {103A24C633}>)

Backtrace:
  0: (sb-ext:native-namestring nil) [external]
  1: (sb-ext:run-program nil ("--user-data-dir=/tmp/plot/chrome-data" "--no-default-browser-check=1" "--no-first-run=1" "--window-size=800,600" "--app=file:///tmp/plot/hp-mpg.html") :env nil :environment n..
  2: (uiop/launch-program:launch-program (nil "--user-data-dir=/tmp/plot/chrome-data" "--no-default-browser-check=1" "--no-first-run=1" "--window-size=800,600" "--app=file:///tmp/plot/hp-mpg.html") :ignore..
  3: (sb-int:simple-eval-in-lexenv (plot:plot (vega:defplot hp-mpg (sb-int:quasiquote #))) #<NULL-LEXENV>)
  4: (eval (plot:plot (vega:defplot hp-mpg (sb-int:quasiquote #))))
  5: ((lambda nil :in swank:interactive-eval))
 --more--
```

I did follow the backtrace to discover the graph I wanted was in `/tmp/plot/` and I just needed to load it manually into firefox to view. What is this error though? I assume firefox should automagically open the graph for me.

I am running sbcl 2.2.11-1 on Artix Linux s6. I also am using ultralisp, as according to [https://github.com/Lisp-Stat/lisp-stat/issues/13](https://github.com/Lisp-Stat/lisp-stat/issues/13) it can help.

**Comment by snunez1** [comment]
Firefox is supposed to automagically open and display the plot, but the whole "fire up the browser and point it to a file to display" thing is fragile.  We're working on alternative that uses webview, but that's a few months away.  Perhaps the easiest thing to do in the meantime would be to try and install Chrome.  Next I would look at [browser.lisp](https://github.com/Lisp-Stat/plot/blob/master/src/plot/browser.lisp) and see if any of the settings there can be changed.  I notice that it's passing chrome flags to Firefox, and that's definitely not going to work.

I don't have a Linux machine to test with, but @tobyWorland did a lot of the Linux work in this area and might have some suggestions.

**Comment by tobyWorland** [comment]
In short, try `(setf plot:*default-browser-command* :default)`

The browser code only works with either chrome or the user's default browser. The intent of the code (afik) is to open a separate instance of the user's browser without toolbars and show only the plot, and Firefox has dropped support for this. Since it wasn't possible to make the behaviour consistent I never tried to work on the Firefox part and to my knowledge it is currently broken on every platform, not just Linux.

If you tell plot to use the user's default browser, it doesn't bother with this and just opens the plot in whatever browser you have set as default. So, if your default browser is Firefox it should just open in a new tab.

As this is starting to cause problems, I'll submit a fix for selecting Firefox when I get the chance.

**Comment by brandflake11** [comment]
Thank you @tobyWorland, :default worked. I'm glad it was as simple as setting a variable! :)
